<?php include('connection.php')?>

<!-- for error hide -->
<?php
error_reporting(0);
?>
<!-- for error hide -->

<?php
// $entered_event_name = Null;
// if (isset($_POST['event_name'])) {
$entered_event_name = $_POST['event_name'];
$sql = 'SELECT * FROM audience WHERE reg_event ="'.$entered_event_name.'"';
$retval = mysqli_query($con,$sql);
// }
?>

<?php include('includes/head.php')?>

<div class="concontainer-fluid container text-center display-none" id="">
      <form method="POST">
        <h1>Select Event List</h1>
        <select name="event_name" class="form-control">
          <option>Select Event List</option>
          <?php
                $sql = 'SELECT * FROM events WHERE event_type= "Solo"';
                $res = mysqli_query($con,$sql);
                ?>
            <?php  while($row = mysqli_fetch_assoc($res))
                {
                  ?>
                <option name="add_event_name">
                  <?php   echo $row['event_name']?>
                  <?php
                    }
                    ?>
                </option>
              </select>
              <br>
              <input type="submit" class="btn btn-warning w-25">
      </form>

    </div>
<div class="container bg-white rounded p-4" >
  <div class="row justify-content-center mb-4">
  <div class="text-theme text-center">
      <h1 class="pt-0">ZEST 2022 Student Registered Details</h1>
      <!-- <h4 class="pt-0">Student Details</h4><br> -->
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Event Name</th>
            <td class="align-left py-2" width=30><?php echo $entered_event_name ?></td>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30>Admin </td> 
          </tr>
          <tr>
         
          <th class="align-middle py-2" width=20% scope="row">Event Time</th>
            <td class="align-left py-2"> <?php  ?> </td>
            <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo "". date("Y-m-d") .""; ?></td>
            <?php
   
            ?>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Student List</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
          <th scope="col" style="width:11%">EID</th>
              <th scope="col" style="width:11%">PID</th>
              <th scope="col" style="width:14%">Student Name</th>
              <th scope="col" style="width:14%">College Name</th>
              <th scope="col" style="width:15%">Event Name</th>
              <th scope="col" style="width:17%">Venue</th>
            </tr>
            <!-- <th scope="col" style="width:25%">Action </th> -->
          </tr>
        </thead>
        <tbody>
        <?php
   while ($row = mysqli_fetch_assoc($retval)) {
    if ($row['eid']>0) {
      # code...
    ?>
          <tr>
            <td>
              <?php
         echo $row["eid"];
         $eid = $row["eid"];
         ?>
            </td>
            
            <td>
              <?php
         echo $row["pid"];
         ?>
            </td>
            <?php
                $qry21 ="SELECT * from pid WHERE pid ='".$row['pid']."'";
                $res211 = mysqli_query($con,$qry21);
                $row2 = mysqli_fetch_assoc($res211);
                ?>
            <td><?php echo $row2["name"];?></td>
            <td><?php echo $row2["college"];?></td>
            <td>
              <?php
         echo $row["reg_event"]
         ?>
            </td>
            <td>
              <?php
         echo $row["venue"]
         ?>
            </td>
          </tr>
          <?php
    }
      
   }
   ?>
        </tbody>
      </table>
    </div>
    <div class="">
    <p class="text-left mt-5" ><b style="border-top:1px solid #000;">* Note:This should be verified and Signed By Head Coordinator.</b></p>  
    <p class="text-right mt-5" ><b style="border-top:1px solid #000;">VERIFIED BY</b></p>
    </div>
    <!-- {% endif %} -->
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <!-- <a href="register_event.php" class="btn btn-color serach-btn mx-2">Register for Event</a> -->
      </form>
    </div>
  </div>
  </div>
</div>
<div class="d-flex" id="wrapper">
  <!-- Page content wrapper-->
  <div id="page-content-wrapper">
    <?php include('includes/navbar.php')?>
    <!-- Page content-->
    
  </div>
</div>

   
<?php include('includes/footer.php')?>