<?php include('includes/head.php')?>
<?php include('connection.php')?>
<?php
session_start();
$_SESSION['f_tid'] = $_GET['TID'];
$qry1 ="SELECT * from tid WHERE TID ='".$_GET['TID']."'";

$res11 = mysqli_query($con,$qry1);
$row = mysqli_fetch_assoc($res11);

?>
<body>
<?php include('includes/navbar.php')?>
<div class="container bg-white rounded p-5">
<div class="row justify-content-center mb-4">
    <div class="text-theme text-center">
      <h1 class="pt-0">ZEST 2022 Student Registered Details</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=30% scope="row">PID</th>
            <td class="align-left py-2" width=60%><?php echo $row['TID'] ?></td>

          </tr>
          <tr>
            <!-- <th class="align-middle py-2" width=20% scope="row">College Name</th>
            <td class="align-left py-2" width=30%><?php echo $row['college'] ?></td> -->
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30><?php echo $row['generated_by'] ?></td>
          </tr>
          <tr>
          <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo $row['date'] ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Event</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
          <th scope="col" style="width:10%">PID in <?php echo $_GET['TID'];?> </th>  
          <th scope="col" style="width:25%">Student Name</th>
          <th scope="col" style="width:15%">College Name</th>
          <th scope="col" style="width:20%">Event Name </th>
          <th scope="col" style="width:15%">Event Date</th>
            <th scope="col" style="width:10%">Event Venue </th>
          </tr>
        </thead>
        <tbody>
        <?php
            $res1 = mysqli_query($con,"SELECT * FROM audience WHERE tid= '".$_GET['TID']."' ");
            while ($ress1 = mysqli_fetch_assoc($res1)) 
            {
              if($ress1['eid'] > 0){
             $pid =$ress1['pid'];
            ?>
        <tr>
                <td><?php echo $ress1['pid']?></td>
                <?php
                $qry21 ="SELECT * from pid WHERE pid ='".$ress1['pid']."'";
                $res211 = mysqli_query($con,$qry21);
                $row2 = mysqli_fetch_assoc($res211);
                ?>
                <td><?php echo $row2['name'] ?></td>
                <td><?php echo $row2['college'] ?></td>
                <td><?php echo $ress1['reg_event']?></td>
                <td><?php echo $ress1['event_date']?></td>
                <td><?php echo $ress1['venue']?></td>
            <?php
              }
            }
            ?>
        </tbody>
      </table>
    </div>
    <div class="">
    <p class="text-left mt-5" ><b style="border-top:1px solid #000;">* Note:This should be verified and Signed By Head Coordinator.</b></p>  
    <p class="text-right mt-5" ><b style="border-top:1px solid #000;">VERIFIED BY</b></p>
    </div>
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <a href="find_pid_registration_team.php" class="btn btn-color serach-btn mx-2">Register for Event</a>
      </form>
    </div>
  </div>
  </div>
</div>
<?php include('includes/footer.php')?>